// demos/src/Examples/CodeBlockLanguage/Vue/CodeBlockComponent.vue
<template>
  <node-view-wrapper class="code-block">
    <select contenteditable="false" v-model="selectedLanguage">
      <option :value="null">
        auto
      </option>
      <option disabled>
        —
      </option>
      <option v-for="(language, index) in languages" :value="language" :key="index">
        {{ language }}
      </option>
    </select>
    <pre><code><node-view-content /></code></pre>
  </node-view-wrapper>
</template>

<script>
import { NodeViewWrapper, NodeViewContent, nodeViewProps } from '@tiptap/vue-3'

export default {
  components: {
    NodeViewWrapper,
    NodeViewContent,
  },

  props: nodeViewProps,

  data() {
    return {
      languages: this.extension.options.lowlight.listLanguages(),
    }
  },

  computed: {
    selectedLanguage: {
      get() {
        return this.node.attrs.language
      },
      set(language) {
        this.updateAttributes({ language })
      },
    },
  },
}
</script>

<style lang="scss">
.code-block {
  position: relative;

  select {
    position: absolute;
    top: 0.5rem;
    right: 0.5rem;
  }
}
</style>

// docs/src/demos/Examples/CodeBlockLanguage/React/CodeBlockComponent.jsx
import React from 'react'
import { NodeViewWrapper, NodeViewContent } from '@tiptap/react'
import './CodeBlockComponent.scss'

export default class CodeBlockComponent extends React.Component {
  constructor(props) {
    super(props)

    this.state = {
      selectedLanguage: props.node.attrs.language,
    }
  }

  render() {
    const { selectedLanguage } = this.state
    const { updateAttributes, extension } = this.props

    return (
      <NodeViewWrapper className="code-block">
        <select contentEditable={false} defaultValue={selectedLanguage} onChange={event => updateAttributes({ language: event.target.value })}>
          <option value="null">
            auto
          </option>
          <option disabled>
            —
          </option>
          {extension.options.lowlight.listLanguages().map((language, index) => (
            <option value={language} key={index}>
              {language}
            </option>
          ))}
        </select>
        <pre><NodeViewContent as="code" /></pre>
      </NodeViewWrapper>
    )
  }
}
