// packages/svelte/src/components/NodeViewWrapper.svelte
<script lang="ts">
  import { getContext } from 'svelte'
  import type { Snippet } from 'svelte'

  let { as = 'div', class: className, children }: { as?: string; class?: string; children?: Snippet } = $props()

  let onDragStart = getContext<(event: DragEvent) => void>('onDragStart')
  let decorationClasses = getContext<string>('decorationClasses')

  let combinedClass = [decorationClasses, className].filter(Boolean).join(' ') || undefined
</script>

<svelte:element this={as} data-node-view-wrapper="" class={combinedClass} style="white-space: normal" ondragstart={onDragStart}>
  {#if children}
    {@render children()}
  {/if}
</svelte:element>

// packages/solid/src/NodeViewWrapper.tsx
import type { JSX } from 'solid-js'
import { splitProps } from 'solid-js'

import { useSolidNodeView } from './useSolidNodeView.jsx'

export type NodeViewWrapperProps = JSX.HTMLAttributes<HTMLDivElement> & {
  as?: string
}

export function NodeViewWrapper(props: NodeViewWrapperProps) {
  const [local, rest] = splitProps(props, ['as', 'class', 'classList'])
  const context = useSolidNodeView()

  return (
    <div
      classList={{
        ...(typeof local.classList === 'object' ? local.classList : {}),
        [context.decorationClasses ?? '']: Boolean(context.decorationClasses),
      }}
      class={[local.class, context.decorationClasses].filter(Boolean).join(' ')}
      style={{ 'white-space': 'normal' }}
      data-node-view-wrapper=""
      onDragStart={context.onDragStart}
      {...rest}
    />
  )
}
