// packages/react-experimental/src/NodeViewContent.tsx
/** @jsxImportSource react */
import type { ComponentProps } from 'react'
import React from 'react'

import { useReactNodeView } from './useReactNodeView.js'

export type NodeViewContentProps<T extends keyof React.JSX.IntrinsicElements = 'div'> = {
  as?: NoInfer<T>
} & ComponentProps<T>

export function NodeViewContent<T extends keyof React.JSX.IntrinsicElements = 'div'>({
  as: Tag = 'div' as T,
  ...props
}: NodeViewContentProps<T>) {
  const { nodeViewContentRef, nodeViewContentChildren } = useReactNodeView()

  return (
    // @ts-ignore
    <Tag
      {...props}
      ref={nodeViewContentRef}
      data-node-view-content=""
      style={{
        whiteSpace: 'pre-wrap',
        ...props.style,
      }}
    >
      {nodeViewContentChildren}
    </Tag>
  )
}

// packages/solid/src/NodeViewContent.tsx
import { Dynamic } from 'solid-js/web'

import { useSolidNodeView } from './useSolidNodeView.js'
import type { DomElement, DomElementAsProps } from './utils/types.js'

export type NodeViewContentProps<E extends DomElement = 'div'> = DomElementAsProps<E>

export function NodeViewContent<E extends DomElement = 'div'>(props: NodeViewContentProps<E>) {
  const context = useSolidNodeView()
  return (
    <Dynamic
      component={props.as || ('div' as any)}
      {...props}
      ref={context.nodeViewContentRef}
      data-node-view-content=""
      style={{
        whiteSpace: 'pre-wrap',
        ...props.style,
      }}
    >
      {context.nodeViewContentChildren}
    </Dynamic>
  )
}
