// demos/src/Extensions/TableOfContents/Vue/ToC.vue
<template>
  <template v-if="items.length === 0">
    <ToCEmptyState />
  </template>
  <template v-else>
    <ToCItem
      v-for="(item, i) in items"
      :key="item.id"
      :item="item"
      :index="i + 1"
      @item-click="onItemClick"
    />
  </template>
</template>

<script>
import { TextSelection } from '@tiptap/pm/state'
import { defineComponent } from 'vue'

import ToCEmptyState from './ToCEmptyState.vue'
import ToCItem from './ToCItem.vue'

export default defineComponent({
  components: {
    ToCItem,
    ToCEmptyState,
  },

  props: {
    items: {
      type: Array,
      default: () => [],
    },
    editor: {
      type: Object,
      required: true,
    },
  },

  methods: {
    onItemClick(e, id) {
      if (this.editor) {
        const element = this.editor.view.dom.querySelector(`[data-toc-id="${id}"`)
        const pos = this.editor.view.posAtDOM(element, 0)

        // set focus
        const tr = this.editor.view.state.tr

        tr.setSelection(new TextSelection(tr.doc.resolve(pos)))

        this.editor.view.dispatch(tr)

        this.editor.view.focus()

        // oxlint-disable-next-line
        if (history.pushState) {
          // oxlint-disable-next-line
          history.pushState(null, null, `#${id}`)
        }

        window.scrollTo({
          top: element.getBoundingClientRect().top + window.scrollY,
          behavior: 'smooth',
        })
      }
    },
  },
})
</script>

// demos/src/Extensions/TableOfContents/React/ToC.jsx
import { TextSelection } from '@tiptap/editor/pm/state'

export const ToCItem = ({ item, onItemClick }) => {
  return (
    <div
      className={`${item.isActive && !item.isScrolledOver ? 'is-active' : ''} ${item.isScrolledOver ? 'is-scrolled-over' : ''}`}
      style={{
        '--level': item.level,
      }}
    >
      <a
        href={`#${item.id}`}
        onClick={e => onItemClick(e, item.id)}
        data-item-index={item.itemIndex}
      >
        {item.textContent}
      </a>
    </div>
  )
}

export const ToCEmptyState = () => {
  return (
    <div className="empty-state">
      <p>Start editing your document to see the outline.</p>
    </div>
  )
}

export const ToC = ({ items = [], editor }) => {
  if (items.length === 0) {
    return <ToCEmptyState />
  }

  const onItemClick = (e, id) => {
    e.preventDefault()

    if (editor) {
      const element = editor.view.dom.querySelector(`[data-toc-id="${id}"`)
      const pos = editor.view.posAtDOM(element, 0)

      // set focus
      const tr = editor.view.state.tr

      tr.setSelection(new TextSelection(tr.doc.resolve(pos)))

      editor.view.dispatch(tr)

      editor.view.focus()

      // oxlint-disable-next-line
      if (history.pushState) {
        // oxlint-disable-next-line
        history.pushState(null, null, `#${id}`)
      }

      window.scrollTo({
        top: element.getBoundingClientRect().top + window.scrollY,
        behavior: 'smooth',
      })
    }
  }

  return (
    <>
      {items.map((item, i) => (
        <ToCItem onItemClick={onItemClick} key={item.id} item={item} index={i + 1} />
      ))}
    </>
  )
}
