// demos/src/Tutorials/1-1-textarea/React/Note.tsx
import './styles.css'

import React, { useState } from 'react'

import { TNote } from './types.js'

export default ({ note }: { note: TNote }) => {
  const [modelValue, setModelValue] = useState(note.content)

  return (
    <textarea onChange={e => setModelValue(e.target.value)} value={modelValue}
              className="p-2 border border-black rounded-lg"
    ></textarea>
  )
}

// demos/src/Tutorials/1-1-textarea/Vue/Note.vue
<script setup lang="ts">

import { ref, watch } from 'vue'

import { TNote } from './types'

const props = defineProps<{ note: TNote }>()

const modelValueProxy = ref('')

watch(props, () => modelValueProxy.value = props.note?.content, {
  immediate: true,
})

</script>

<template>
  <textarea v-model="modelValueProxy" class="p-2 border border-black rounded-lg"></textarea>
</template>
