// demos/src/Extensions/DragHandleWithNodeViews/React/extensions/recommendation/views/RecommendationView.jsx
import { NodeViewWrapper } from '@tiptap/react'

export const RecommendationView = ({ node, position }) => {
  return (
    <NodeViewWrapper data-drag-handle>
      <div className="title">Recommendation {node.attrs.id}</div>
      <p>Test</p>
      <small style={{ opacity: 0.5 }}>pos: {position}</small>
    </NodeViewWrapper>
  )
}

// demos/src/Extensions/DragHandleWithNodeViews/Vue/extensions/recommendation/views/RecommendationView.vue
<template>
  <node-view-wrapper data-drag-handle class="node-recommendation">
    <div class="title">Recommendation {{ node.attrs.id }}</div>
    <p>Test</p>
    <small style="opacity: 0.5">pos: {{ position }}</small>
  </node-view-wrapper>
</template>

<script>
import { nodeViewProps, NodeViewWrapper } from '@tiptap/vue-3'

export default {
  components: {
    NodeViewWrapper,
  },

  props: nodeViewProps,
}
</script>
